
version: "3.8"

services:
  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nuxt-app
    ports:
      - "3000:3000"
    restart: unless-stopped
    working_dir: /app
    volumes:
    - C:\002 elfjane\vm\visua_gen:/app
